"""change user model

Revision ID: 064163ca3a2f
Revises: 512f6a963bfe
Create Date: 2023-03-08 18:15:18.961967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064163ca3a2f'
down_revision = '512f6a963bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
